Repository AY2425S1-CS2113-W10-1/tp, pull requests merged in 2024-11, with the labels that each got.

#122 Update input.txt and EXPECTED.TXT for Budget display
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Enhancement, severity.Low

#131 Add JUnit tests for Budget-related classes
  src/main/java/seedu/budgetbuddy/commands/budget/AddBudgetCommand.java
  src/main/java/seedu/budgetbuddy/commands/budget/DeductBudgetCommand.java
  src/main/java/seedu/budgetbuddy/commands/budget/ListBudgetCommand.java
  src/main/java/seedu/budgetbuddy/validators/budget/ListBudgetValidator.java
  src/test/java/seedu/budgetbuddy/commands/budget/ListBudgetCommandTest.java
  src/test/java/seedu/budgetbuddy/validators/budget/AddBudgetValidatorTest.java
  src/test/java/seedu/budgetbuddy/validators/budget/DeductBudgetValidatorTest.java
  src/test/java/seedu/budgetbuddy/validators/budget/ListBudgetValidatorTest.java
Labels: JUnit

#135 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/AddBudgetSequenceDiagram.drawio.png
  docs/diagrams/DeductBudgetSequenceDiagram.drawio.png
  docs/diagrams/DisplayIncomeSpentSequenceDiagram.drawio.png
  docs/diagrams/ListBudgetSequenceDiagram.drawio.png
Labels: type.Task, v2.0

#137 Developer Guide update
  docs/DeveloperGuide.md
  docs/diagrams/AddExpenseSequenceDiagram.drawio.png
  docs/diagrams/DeleteExpenseSequenceDiagram.drawio.png
  docs/diagrams/ExpenseAndIncomeClassDiagram.drawio.png
  docs/diagrams/ListRemainingBudgetSequenceDiagram.drawio.png
Labels: type.Task, v2.0

#142 Update DG and Fix Functions Bugs
  data/BudgetBuddy.txt
  docs/DeveloperGuide.md
  docs/diagrams/EditSequenceDiagram.drawio.png
  docs/diagrams/EditSequenceDiagram2.drawio.png
  docs/diagrams/ListExpenseSequenceDiagram.drawio.png
  docs/diagrams/ListIncomeSequenceDiagram.drawio.png
  logs/app.log
  src/main/java/seedu/budgetbuddy/Parser.java
  src/main/java/seedu/budgetbuddy/commands/expense/EditExpenseCommand.java
  src/main/java/seedu/budgetbuddy/commands/income/EditIncomeCommand.java
  src/main/java/seedu/budgetbuddy/transaction/expense/ExpenseManager.java
  src/main/java/seedu/budgetbuddy/transaction/income/IncomeManager.java
  src/main/java/seedu/budgetbuddy/validators/CategoryValidator.java
  src/main/java/seedu/budgetbuddy/validators/expense/EditExpenseValidator.java
  src/main/java/seedu/budgetbuddy/validators/expense/ListExpenseValidator.java
  src/main/java/seedu/budgetbuddy/validators/income/EditIncomeValidator.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug, priority.Medium, v2.0

#146 Standardize list command
  src/main/java/seedu/budgetbuddy/commands/expense/ListExpenseCommand.java
  src/main/java/seedu/budgetbuddy/commands/income/ListIncomeCommand.java
  src/main/java/seedu/budgetbuddy/validators/expense/ListExpenseValidator.java
  src/main/java/seedu/budgetbuddy/validators/income/ListIncomeValidator.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, v2.0

#148 Edit DG sequence diagrams according to comments
  data/BudgetBuddy.txt
  docs/DeveloperGuide.md
  docs/diagrams/BreakdownExpenseSequenceDiagram.drawio.png
  docs/diagrams/DisplayHelpSequenceDiagram.drawio.png
  docs/diagrams/DisplaySavingsSequenceDiagram.drawio.png
  docs/diagrams/SearchExpenseSequenceDiagram.drawio-3.png
  docs/diagrams/SearchExpenseSequenceDiagram.drawio.png
  logs/app.log
  src/main/java/seedu/budgetbuddy/transaction/saving/SavingsManager.java
  src/test/java/seedu/budgetbuddy/transaction/saving/SavingsManagerTest.java
Labels: type.Enhancement, priority.High

#151 Add JUnit Tests for display income spent
  data/BudgetBuddy.txt
  docs/DeveloperGuide.md
  logs/app.log
  src/main/java/seedu/budgetbuddy/Ui.java
  src/main/java/seedu/budgetbuddy/commands/budget/ListBudgetCommand.java
  src/main/java/seedu/budgetbuddy/commands/income/DisplayIncomeSpentCommand.java
  src/main/java/seedu/budgetbuddy/transaction/budget/Budget.java
  src/main/java/seedu/budgetbuddy/transaction/budget/BudgetManager.java
  src/main/java/seedu/budgetbuddy/validators/budget/DeductBudgetValidator.java
  src/main/java/seedu/budgetbuddy/validators/income/DisplayIncomeSpentValidator.java
  src/test/java/seedu/budgetbuddy/commands/income/DisplayIncomeSpentCommandTest.java
  src/test/java/seedu/budgetbuddy/validators/budget/DeductBudgetValidatorTest.java
  src/test/java/seedu/budgetbuddy/validators/income/DisplayIncomeSpentValidatorTest.java
  text-ui-test/EXPECTED.TXT
Labels: v2.0, JUnit

#157 Add PPP
  docs/team/chinorea.md
Labels: type.Task

#158 Update PPP
  docs/team/ziliaajy.md
Labels: v2.1

#214 Remove first income and first expense display for DisplaySavings feature
  data/BudgetBuddy.txt
  logs/app.log
  logs/app.log.1
  src/main/java/seedu/budgetbuddy/transaction/saving/SavingsManager.java
  src/test/java/seedu/budgetbuddy/transaction/saving/SavingsManagerTest.java
Labels: type.Enhancement, v2.1

#215 Display all savings numbers in 2 decimal places.
  logs/app.log
  logs/app.log.1
  src/main/java/seedu/budgetbuddy/transaction/saving/SavingsManager.java
  src/test/java/seedu/budgetbuddy/transaction/saving/SavingsManagerTest.java
Labels: type.Enhancement

#216 Edit SearchExpenseCommand and SearchExpenseValidator
  logs/app.log
  src/main/java/seedu/budgetbuddy/commands/expense/SearchExpenseCommand.java
  src/main/java/seedu/budgetbuddy/validators/expense/SearchExpenseValidator.java
Labels: type.Bug, severity.Medium

#217 Create PPP document
  docs/team/chuacleon.md
Labels: priority.High

#218 Edit displayHelpMessage method to display features to new user.
  logs/app.log
  src/main/java/seedu/budgetbuddy/Ui.java
Labels: type.Bug, severity.Medium

#219 Edit isCommand() method of BreakdownExpensesCommand
  logs/app.log
  src/main/java/seedu/budgetbuddy/commands/expense/BreakdownExpensesCommand.java
Labels: type.Bug, priority.Medium, severity.Medium

#222 Add JUnit test for Expense Manager to improve coverage
  data/BudgetBuddy.txt
  logs/app.log
  logs/app.log.1
  src/test/java/seedu/budgetbuddy/transaction/expense/ExpenseManagerTest.java
Labels: JUnit

#223 Update Project Portfolio Page.
  data/BudgetBuddy.txt
  docs/team/chuacleon.md
  logs/app.log
Labels: priority.High

#224 Change "search expense" to "search expenses" in User Guide.
  data/BudgetBuddy.txt
  docs/UserGuide.md
  src/main/java/seedu/budgetbuddy/Ui.java
Labels: priority.High

#225 Add PPP file
  docs/team/telferang.md
Labels: type.Task, v2.1

#226 Fix issues from PE-D
  data/BudgetBuddy.txt
  docs/UserGuide.md
  docs/images/EditExpense_ExpectedOutput.png
  docs/images/EditIncomes_ExpectedOutput.png
  logs/app.log
  src/main/java/seedu/budgetbuddy/transaction/expense/ExpenseManager.java
  src/main/java/seedu/budgetbuddy/transaction/income/IncomeManager.java
  src/main/java/seedu/budgetbuddy/validators/DateValidator.java
  src/main/java/seedu/budgetbuddy/validators/expense/EditExpenseValidator.java
  src/main/java/seedu/budgetbuddy/validators/income/EditIncomeValidator.java
Labels: type.Bug

#227 Update PPP and add placeholder image
  docs/AboutUs.md
  docs/images/Portrait_placeholder.png
  docs/team/chinorea.md
Labels: type.Task, v2.1

#228 Fix PE-D issues
  data/BudgetBuddy.txt
  docs/UserGuide.md
  docs/images/AddBudgets_ExpectedOutputs.png
  docs/images/DeductBudgets_ExpectedOutputs.png
  docs/images/DisplayIncomeSpent_ExpectedOutputs.png
  docs/images/ListBudgets_ExpectedOutput.png
  logs/app.log
  logs/app.log.1
  logs/app.log.2
  logs/app.log.2.lck
  src/main/java/seedu/budgetbuddy/transaction/budget/Budget.java
  src/main/java/seedu/budgetbuddy/transaction/budget/BudgetManager.java
  src/main/java/seedu/budgetbuddy/validators/AmountValidator.java
  src/main/java/seedu/budgetbuddy/validators/budget/AddBudgetValidator.java
  src/main/java/seedu/budgetbuddy/validators/budget/DeductBudgetValidator.java
  src/main/java/seedu/budgetbuddy/validators/budget/ListBudgetValidator.java
  src/main/java/seedu/budgetbuddy/validators/income/DisplayIncomeSpentValidator.java
  src/test/java/seedu/budgetbuddy/transaction/budget/BudgetTest.java
  src/test/java/seedu/budgetbuddy/validators/budget/AddBudgetValidatorTest.java
  src/test/java/seedu/budgetbuddy/validators/budget/DeductBudgetValidatorTest.java
  src/test/java/seedu/budgetbuddy/validators/budget/ListBudgetValidatorTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug

#229 Update PPP
  data/BudgetBuddy.txt
  docs/DeveloperGuide.md
  docs/team/johndoe.md
  docs/team/ziliaajy.md
Labels: type.Task, v2.1

#231 Branch PED bug
  docs/UserGuide.md
  docs/images/AddExpense_Expected_Output.png
  docs/images/AddIncome_Expected_Output.png
  docs/images/DeleteExpense_Expected_Output.png
  docs/images/DeleteIncome_Expected_Output.png
  docs/images/ListRemainingBudget_Expected_Output.png
  docs/team/telferang.md
  src/main/java/seedu/budgetbuddy/Parser.java
  src/main/java/seedu/budgetbuddy/transaction/Transaction.java
  src/main/java/seedu/budgetbuddy/transaction/budget/Budget.java
  src/main/java/seedu/budgetbuddy/transaction/budget/RemainingBudgetManager.java
  src/main/java/seedu/budgetbuddy/transaction/expense/Expense.java
  src/main/java/seedu/budgetbuddy/transaction/expense/ExpenseManager.java
  src/main/java/seedu/budgetbuddy/transaction/income/IncomeManager.java
  src/main/java/seedu/budgetbuddy/validators/expense/AddExpenseValidator.java
  src/test/java/seedu/budgetbuddy/transaction/budget/BudgetTest.java
  src/test/java/seedu/budgetbuddy/transaction/budget/RemainingBudgetManagerTest.java
  src/test/java/seedu/budgetbuddy/transaction/expense/ExpenseManagerTest.java
  src/test/java/seedu/budgetbuddy/validators/expense/AddExpenseValidatorTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug

#236 Update PPP
  docs/team/ziliaajy.md
Labels: type.Task, v2.1

#235 Fix PE-D issues
  data/BudgetBuddy.txt
  docs/UserGuide.md
  docs/diagrams/EditSequenceDiagram.drawio.png
  docs/diagrams/EditSequenceDiagram2.drawio.png
  docs/images/EditExpense_ExpectedOutput.png
  docs/images/EditIncomes_ExpectedOutput.png
  docs/images/ListExpensesWithFilter_ExpectedOutput.png
  docs/images/ListExpenses_ExpectedOutput.png
  docs/images/ListIncomesWithFilter_ExpectedOutput.png
  docs/images/ListIncomes_ExpectedOutput.png
  docs/team/chinorea.md
  src/main/java/seedu/budgetbuddy/Ui.java
  src/main/java/seedu/budgetbuddy/commands/expense/EditExpenseCommand.java
  src/main/java/seedu/budgetbuddy/commands/income/EditIncomeCommand.java
  src/main/java/seedu/budgetbuddy/transaction/expense/ExpenseManager.java
  src/test/java/seedu/budgetbuddy/transaction/expense/ExpenseManagerTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task, type.Bug, v2.1

#242 Update UG
  docs/UserGuide.md
Labels: type.Task
