Repository AY2425S1-CS2113-W10-1/tp, pull requests merged in 2024-10, with the labels that each got.

#29 Refactor and improve Budget and BudgetManager tests
  src/test/java/seedu/budgetbuddy/transaction/budget/BudgetManagerTest.java
  src/test/java/seedu/budgetbuddy/transaction/budget/BudgetTest.java
Labels: severity.Low, JUnit

#30 Add JUnit test for DisplayExpense Feature
  src/main/java/seedu/budgetbuddy/commands/DisplayExpenseCommand.java
  src/main/java/seedu/budgetbuddy/transaction/expense/ExpenseManager.java
  src/test/java/seedu/budgetbuddy/transaction/expense/ExpenseManagerTest.java
  src/test/java/seedu/budgetbuddy/validators/DisplayExpenseValidatorTest.java
Labels: JUnit

#33 Branch search expense
  src/main/java/seedu/budgetbuddy/transaction/expense/ExpenseManager.java
  src/test/java/seedu/budgetbuddy/transaction/expense/ExpenseManagerTest.java
Labels: type.Task, JUnit

#34 Add JUnit test Validator and Manager
  src/main/java/seedu/budgetbuddy/commands/AddExpenseCommand.java
  src/main/java/seedu/budgetbuddy/commands/IncorrectCommand.java
  src/test/java/seedu/budgetbuddy/transaction/income/IncomeManagerTest.java
  src/test/java/seedu/budgetbuddy/validators/AddExpenseValidatorTest.java
Labels: JUnit

#39 Add Code Defense to DisplayExpense Feature
  data/BudgetBuddy.txt
  src/main/java/seedu/budgetbuddy/commands/DisplayExpenseCommand.java
  src/main/java/seedu/budgetbuddy/transaction/expense/ExpenseManager.java
  src/main/java/seedu/budgetbuddy/validators/DisplayExpenseValidator.java
Labels: type.Task, v1.0

#57 As a user, I can set a monthly budget for each category
  data/BudgetBuddy.txt
  logs/app.log
  src/main/java/seedu/budgetbuddy/Parser.java
  src/main/java/seedu/budgetbuddy/Storage.java
  src/main/java/seedu/budgetbuddy/commands/budget/AddBudgetCommand.java
  src/main/java/seedu/budgetbuddy/commands/budget/DeductBudgetCommand.java
  src/main/java/seedu/budgetbuddy/commands/expense/AddExpenseCommand.java
  src/main/java/seedu/budgetbuddy/commands/expense/DisplayExpenseCommand.java
  src/main/java/seedu/budgetbuddy/transaction/Category.java
  src/main/java/seedu/budgetbuddy/transaction/budget/Budget.java
  src/main/java/seedu/budgetbuddy/transaction/budget/BudgetManager.java
  src/main/java/seedu/budgetbuddy/transaction/expense/Expense.java
  src/main/java/seedu/budgetbuddy/transaction/expense/ExpenseManager.java
  src/main/java/seedu/budgetbuddy/validators/CategoryValidator.java
  src/main/java/seedu/budgetbuddy/validators/budget/AddBudgetValidator.java
  src/main/java/seedu/budgetbuddy/validators/budget/DeductBudgetValidator.java
  src/main/java/seedu/budgetbuddy/validators/expense/AddExpenseValidator.java
  src/main/java/seedu/budgetbuddy/validators/expense/DisplayExpenseValidator.java
  src/test/java/seedu/budgetbuddy/transaction/budget/BudgetManagerTest.java
  src/test/java/seedu/budgetbuddy/transaction/budget/BudgetTest.java
  src/test/java/seedu/budgetbuddy/transaction/expense/ExpenseManagerTest.java
  src/test/java/seedu/budgetbuddy/validators/AddExpenseValidatorTest.java
  src/test/java/seedu/budgetbuddy/validators/DisplayExpenseValidatorTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Story, priority.Medium, v2.0

#59 Fix add budgets display
  data/BudgetBuddy.txt
  logs/app.log
  src/main/java/seedu/budgetbuddy/commands/budget/AddBudgetCommand.java
  src/main/java/seedu/budgetbuddy/transaction/budget/BudgetManager.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug, severity.Medium

#64 Enhance budget display
  data/BudgetBuddy.txt
  src/main/java/seedu/budgetbuddy/transaction/budget/BudgetManager.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Enhancement, severity.VeryLow, v2.0

#65 Add Edit Expense Function
  logs/app.log
  src/main/java/seedu/budgetbuddy/Parser.java
  src/main/java/seedu/budgetbuddy/Ui.java
  src/main/java/seedu/budgetbuddy/commands/expense/DisplayExpenseCommand.java
  src/main/java/seedu/budgetbuddy/commands/expense/EditExpenseCommand.java
  src/main/java/seedu/budgetbuddy/transaction/Category.java
  src/main/java/seedu/budgetbuddy/transaction/Transaction.java
  src/main/java/seedu/budgetbuddy/transaction/expense/Expense.java
  src/main/java/seedu/budgetbuddy/transaction/expense/ExpenseManager.java
  src/main/java/seedu/budgetbuddy/validators/expense/EditExpenseValidator.java
  src/test/java/seedu/budgetbuddy/commands/expense/EditExpenseCommandTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Story, JUnit

#69 Branch refactor budget
  logs/app.log.lck
  src/main/java/seedu/budgetbuddy/Parser.java
  src/main/java/seedu/budgetbuddy/commands/budget/AddBudgetCommand.java
  src/main/java/seedu/budgetbuddy/transaction/budget/Budget.java
  src/main/java/seedu/budgetbuddy/transaction/budget/RemainingBudgetManager.java
  src/test/java/seedu/budgetbuddy/transaction/budget/BudgetManagerTest.java
  src/test/java/seedu/budgetbuddy/transaction/budget/BudgetTest.java
  src/test/java/seedu/budgetbuddy/transaction/budget/RemainingBudgetManagerTest.java
Labels: type.Task, v2.0

#71 As a user, I can view the percentage of my total income spent
  .gitignore
  data/BudgetBuddy.txt
  logs/app.log
  src/main/java/seedu/budgetbuddy/Parser.java
  src/main/java/seedu/budgetbuddy/commands/income/DisplayIncomeSpentCommand.java
  src/main/java/seedu/budgetbuddy/transaction/expense/ExpenseManager.java
  src/main/java/seedu/budgetbuddy/transaction/income/IncomeManager.java
  src/main/java/seedu/budgetbuddy/transaction/income/IncomeSpent.java
  src/main/java/seedu/budgetbuddy/validators/income/DisplayIncomeSpentValidator.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Story, v2.0

#72 Re-setup logfile
  .gitignore
Labels: type.Bug, severity.Low, v2.0

#74 Update developer guide
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium

#82 Update Developer Guide for Add and Deduct Budget features
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium

#88 Add JUnit Tests
  .gitignore
  logs/app.log.lck
  src/main/java/seedu/budgetbuddy/Storage.java
  src/main/java/seedu/budgetbuddy/validators/expense/ListExpenseValidator.java
  src/test/java/seedu/budgetbuddy/commands/budget/AddBudgetCommandTest.java
  src/test/java/seedu/budgetbuddy/commands/budget/DeductBudgetCommandTest.java
  src/test/java/seedu/budgetbuddy/transaction/budget/BudgetManagerTest.java
  src/test/java/seedu/budgetbuddy/transaction/budget/BudgetTest.java
Labels: v2.0, JUnit

#92 Fix DG contribution
  docs/DeveloperGuide.md
Labels: severity.VeryLow

#94 Refector Storage and edited expenseManager
  data/BudgetBuddy.txt
  src/main/java/seedu/budgetbuddy/BudgetBuddy.java
  src/main/java/seedu/budgetbuddy/Parser.java
  src/main/java/seedu/budgetbuddy/Storage.java
  src/main/java/seedu/budgetbuddy/commands/expense/ListExpenseCommand.java
  src/main/java/seedu/budgetbuddy/commands/income/ListIncomeCommand.java
  src/main/java/seedu/budgetbuddy/transaction/budget/BudgetManager.java
  src/main/java/seedu/budgetbuddy/transaction/expense/ExpenseManager.java
  src/main/java/seedu/budgetbuddy/transaction/income/IncomeManager.java
  src/main/java/seedu/budgetbuddy/validators/expense/ListExpenseValidator.java
  src/test/java/seedu/budgetbuddy/transaction/expense/ExpenseManagerTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug, severity.Medium, v2.0

#106 Branch display expense
  data/BudgetBuddy.txt
  src/main/java/seedu/budgetbuddy/transaction/expense/ExpenseManager.java
  src/test/java/seedu/budgetbuddy/transaction/expense/ExpenseManagerTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, priority.Medium

#108 Add Edit Income Function
  data/BudgetBuddy.txt
  src/main/java/seedu/budgetbuddy/Parser.java
  src/main/java/seedu/budgetbuddy/Ui.java
  src/main/java/seedu/budgetbuddy/commands/expense/EditExpenseCommand.java
  src/main/java/seedu/budgetbuddy/commands/income/EditIncomeCommand.java
  src/main/java/seedu/budgetbuddy/transaction/income/IncomeManager.java
  src/main/java/seedu/budgetbuddy/validators/income/EditIncomeValidator.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Story, priority.Medium

#109 Update DG for Add Budget Feature
  data/BudgetBuddy.txt
  docs/DeveloperGuide.md
  docs/diagrams/AddBudgetSequenceDiagram.drawio.png
  src/main/java/seedu/budgetbuddy/Storage.java
  src/main/java/seedu/budgetbuddy/transaction/budget/BudgetManager.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task, v2.0

#110 Update details in Deduct Budget feature for DG
  docs/DeveloperGuide.md
  docs/diagrams/AddBudgetSequenceDiagram.drawio.png
  docs/diagrams/DeductBudgetSequenceDiagram.drawio.png
Labels: type.Task, v2.0

#111 Fix auto-correction of invalid dates
  data/BudgetBuddy.txt
  src/main/java/seedu/budgetbuddy/validators/DateValidator.java
Labels: type.Bug, severity.Medium

#114 Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddExpenseSequenceDiagram.drawio.png
  docs/diagrams/ExpenseAndIncomeClassDiagram.drawio.png
  docs/diagrams/ListRemainingBudgetSequenceDiagram.drawio.png
  src/main/java/seedu/budgetbuddy/commands/budget/ListRemainingBudgetCommand.java
  src/main/java/seedu/budgetbuddy/commands/income/ListIncomeCommand.java
  src/main/java/seedu/budgetbuddy/transaction/budget/RemainingBudgetManager.java
  src/main/java/seedu/budgetbuddy/validators/expense/DeleteExpenseValidator.java
  src/main/java/seedu/budgetbuddy/validators/income/DeleteIncomeValidator.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task, priority.Medium, v2.0

#115 Update DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/EditExpenseSequenceDiagram.drawio.png
  docs/diagrams/EditIncomeSequenceDiagram.drawio.png
  docs/diagrams/ListExpenseSequenceDiagram.drawio.png
  docs/diagrams/ListIncomeSequenceDiagram.drawio.png
Labels: type.Story, type.Task, priority.Medium, v2.0
